src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 10)]
    private ?string $codePostal = null;

    #[ORM\Column(length: 50)]
    private ?string $ville = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateCommande = null;

    #[ORM\Column(type: Types::BOOLEAN)]
    private ?bool $recupCommande = false;

    #[ORM\OneToMany(mappedBy: 'commande', targetEntity: ProduitCommande::class, cascade: ['persist', 'remove'])]
    private Collection $produitCommandes;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    private ?User $User = null;

    public function __construct()
    {
        $this->produitCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->codePostal;
    }

    public function setCodePostal(string $codePostal): static
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->dateCommande;
    }

    public function setDateCommande(\DateTimeInterface $dateCommande): static
    {
        $this->dateCommande = $dateCommande;

        return $this;
    }

   

    /**
     * @return Collection<int, ProduitCommande>
     */
    public function getProduitCommandes(): Collection
    {
        return $this->produitCommandes;
    }
    

    public function addProduitCommande(ProduitCommande $produitCommande): static
    {
        if (!$this->produitCommandes->contains($produitCommande)) {
            $this->produitCommandes->add($produitCommande);
            $produitCommande->setCommande($this);
        }

        return $this;
    }

    public function removeProduitCommande(ProduitCommande $produitCommande): static
    {
        if ($this->produitCommandes->removeElement($produitCommande)) {
            // set the owning side to null (unless already changed)
            if ($produitCommande->getCommande() === $this) {
                $produitCommande->setCommande(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }

    public function isRecupCommande(): ?bool
    {
        return $this->recupCommande;
    }

    public function setRecupCommande(bool $recupCommande): self
    {
        $this->recupCommande = $recupCommande;
        return $this;
    }
}

templates/_partials/_footer.html.twig
<div class="footer">
	<div class="divFooter">
		<ul class="linkFooter">
			<h3>Information</h3>
			<a href="/#six">Contact</a>
			<a href="{{path('app_mention_footer')}}">Mentions légales</a>
			<a href="{{path('app_condition_footer')}}">Conditions Générales de vente</a>
		</ul>
		<div class="logoFooter">
			<img class="logfoot" src="/assets/img/logo.webp" alt="logo">
		</div>
		<ul class="contactFooter">
			<h3>Contactez-Nous</h3>
			<li>Telephone : 0606650392</li>
			<li><a class="mail" href="mailto:semprini.anthony@gmail.com">Email : semprini.anthony@gmail.com</a></li>
			<li>Adresse : 53 rue de la charmaille</li>
			<li>Code postal : 67200</li>
			<li><strong>Starsbourg</strong></li>
		</ul>
	</div>
</div>

templates/_partials/_nav.html.twig
<header>
    <div class="menu" id="openBtnB">
        <i class="fa-solid fa-bars"></i>
        <p>Menu</p>
    </div>
    <div class="allBurgerNav">
        <div class="burgerNav">
            <div class="styleBurger openNAvB">
                <ul>
                    <li class="closeBtn">x</li>
                    <li><a href="{{path('app_home')}}">Accueil</a></li>
                    <li><a href="{{path('app_produit')}}">Shop</a></li>
                    <li><a href="{{path('app_prestation')}}">Tarifs & RDV</a></li>
                    {% if app.user %}
                    <li><a href="{{ path('app_logout')}}">Se déconnecter</a></li>
                    <li><a href="{{ path('app_profil')}}">Mon profil</a></li>
                    <li><a href="{{ path('app_historique_commandes')}}">Historique des commandes</a></li>
                    <li><a class="panier" href="{{path('app_panier')}}">Panier </a></li>
                    {% if is_granted('ROLE_ADMIN') %}
                    <div class="admin">
                        <a href="{{path('admin')}}">Panneau d'administration</a>
                    </div>
                    {% endif %}
                    {% else %}

                    <div id="myLogB" class="logB">
                        
                        <ul>
                            <li><a href="{{ path('app_login')}}">Se connecter</a></li>
                            <li><a href="{{ path('app_register')}}">S'inscrire</a></li>
                           
                    </div>
                    {% endif %}
                </ul>
            </div>
        </div>


        <div class="allNavBar">
            <div class="navbar">
                <img src="/assets/img/logo.webp" alt="logo">
                <a href="{{path('app_home')}}">Accueil</a>
                <a href="{{path('app_produit')}}">Shop</a>
                <a href="{{path('app_prestation')}}">Tarifs & Prise de RDV</a>

                {% if app.user %}

                <div id="myLog" class="log">
                    <a id="closeBtn" href="#" class="close">&times;</a>
                    <ul>
                        <li><a href="{{ path('app_logout')}}">Se déconnecter</a></li>
                        <li><a href="{{ path('app_profil')}}">Mon profil</a></li>
                        <li><a href="{{ path('app_historique_commandes')}}">Historique des commandes</a></li>
                        <li><a class="panier" href="{{path('app_panier')}}">Panier </a></li>
                        {% if is_granted('ROLE_ADMIN') %}
                        <div class="admin">
                            <a href="{{path('admin')}}">Panneau d'administration</a>
                        </div>
                        {% endif %}
                    </ul>
                    </ul>
                </div>
                <a href="#" id="openBtn">
                    <i class="fa-solid fa-user"></i>
                    <p>{{app.user.pseudo}}</p>
                </a>
                {% else %}

                <div id="myLog" class="log">
                    <a id="closeBtn" href="#" class="close">&times;</a>
                    <ul>
                        <li><a href="{{ path('app_login')}}">Se connecter</a></li>
                        <li><a href="{{ path('app_register')}}">S'inscrire</a></li>
                </div>
                <a href="#" id="openBtn">
                    <i class="fa-solid fa-user-plus"></i>

                </a>
            </div>
            {% endif %}
        </div>
    </div>
</header>

<script>
    var log = document.getElementById("myLog");
    var openBtn = document.getElementById("openBtn");
    var closeBtn = document.getElementById("closeBtn");

    openBtn.onclick = openNav;
    closeBtn.onclick = closeNav;

    /* Set the width of the side navigation to 250px */
    function openNav() {
        log.classList.add("active");
    }

    /* Set the width of the side navigation to 0 */
    function closeNav() {
        log.classList.remove("active");
    }



    document.addEventListener('DOMContentLoaded', function () {
        var openBtn = document.getElementById('openBtnB');
        var closeBtn = document.querySelector('.closeBtn');
        var navBurger = document.querySelector('.burgerNav');

        openBtn.addEventListener('click', function () {
            navBurger.classList.toggle('active');
        });
        closeBtn.addEventListener('click', function () {
            navBurger.classList.remove('active');
        });
    });



</script>