src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5.3)]
    private ?float $prix = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\OneToMany(mappedBy: 'produit', targetEntity: ProduitCommande::class)]
    private Collection $produitCommandes;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    private ?Categorie $Categorie = null;


   
    
    public function __construct()
    {
        $this->produitCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, ProduitCommande>
     */
    public function getProduitCommandes(): Collection
    {
        return $this->produitCommandes;
    }

    public function addProduitCommande(ProduitCommande $produitCommande): static
    {
        if (!$this->produitCommandes->contains($produitCommande)) {
            $this->produitCommandes->add($produitCommande);
            $produitCommande->setProduit($this);
        }

        return $this;
    }

    public function removeProduitCommande(ProduitCommande $produitCommande): static
    {
        if ($this->produitCommandes->removeElement($produitCommande)) {
            // set the owning side to null (unless already changed)
            if ($produitCommande->getProduit() === $this) {
                $produitCommande->setProduit(null);
            }
        }

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->Categorie;
    }

    public function setCategorie(?Categorie $Categorie): static
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Repository\ProduitRepository;
use App\Repository\CategorieRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProduitController extends AbstractController
{
    #[Route('/produit', name: 'app_produit')]
 

#[Route('/produit', name: 'app_produit')]
public function index(ProduitRepository $produitRepository, CategorieRepository $categorieRepository, Request $request, PaginatorInterface $paginator): Response
{
    $category = $request->query->get('category'); // Récupère la catégorie du paramètre de requête

    // Choisissez la bonne requête en fonction de la catégorie
    if ($category) {
        $query = $produitRepository->findByCategory($category);
    } else {
        $query = $produitRepository->paginationQuery();
    }

    $pagination = $paginator->paginate(
        $query,
        $request->query->get('page', 1),
        5 // Nombres d'éléments par page
    );

    $categories = $categorieRepository->findAll();

    return $this->render('produit/index.html.twig', [
        'pagination' => $pagination,
        'currentCategory' => $category,
        'categories' => $categories
    ]);
}



    
    #[Route('/detail{id}', name: 'app_detail_produit')]
    public function detailProduit(Produit $produit): Response
    {
        //redirige vers la vue du detail d'un produit
        return $this->render('produit/detail.html.twig',[
            'produit' => $produit,
        ]
    );
    }
}

templates/produit/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{{produit.nom}}
{% endblock %}

{% block body %}
<div class="detailProd">
	<div class="produitDetail">
		<h1>{{produit}} </h1>
		<h2>Prix : {{produit.prix}} €</h2>
		<div class="place">
			<div class="left">
				<img src="assets/img/{{produit.image}}" alt="img produit">
			</div>
			<div class="rigth">
				<p>Categorie : {{produit.categorie.nom}}</p>
				<p style="text-decoration:underline">Description{{produit.description|raw}}</p>
				<a class="buttonSmall" href="{{path('app_panier_add', {'id': produit.id})}}">Ajouter au panier</a>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Shop{% endblock %}
{% block head %}
<meta name="description"
    content="Découvrez notre gamme de produits de qualité pour les soins capillaires et de barbier. Des produits premium pour prendre soin de vos cheveux et de votre barbe. Trouvez les meilleurs shampooings, huiles, baumes et accessoires pour une apparence soignée. Transformez votre routine de beauté avec nos produits de barbier et de soins capillaires de premier choix." />
{% endblock %}
{% block body %}
<div class="shop">
    <h1>Produits</h1>
    <form action="{{ path('app_produit') }}" method="get">
        <select name="category" class="formElement" onchange="this.form.submit()">
            <option value="">Toutes les catégories</option>
            {% for categorie in categories %}
            <option value="{{ categorie.id }}" {% if currentCategory == categorie.id %}selected{% endif %}>
                {{ categorie.nom }}
            </option>
        {% endfor %}
        </select>
    </form>
    <div class="prodAll">
        {% for produit in pagination %}
        <div class="cardProd">
            <a href="{{path('app_detail_produit', {'id': produit.id})}}"><img src="assets/img/{{produit.image}}"
                    alt="image produit"></a>
            <p>{{produit}} {{produit.prix}}€</p>
            <a href="{{path('app_panier_add', {'id': produit.id})}}" class="buttonSmall">Ajouter au panier</a>
        </div>
        {% endfor %}
    </div>
    {{ knp_pagination_render(pagination)}}
</div>
{% endblock %}